<style>
</style>
<?php
$result = $this->getResult();
$type = $this->getType();
$params = $this->getParams();
?>
<script type="text/javascript"> function PrintDiv(div) {window.print();} </script>
<fieldset>
    <legend>
    <?php
     $dd = sprintf("<span class='big-font'><strong>%1s</strong></span>", $result["employee_name"]);
        echo $dd;
    ?>
	</legend>
	<h3>
	<?php
	
    $dd = sprintf("From <strong>%1s</strong> to <strong>%2s</strong>  (%3s Days)", $result["start_date"], 
        $result["end_date"], $result["total_days"]);
    echo $dd;
    ?>
    </h3>
    
    	<div class="box">
                    <div class="box-content">
                    </div>
            <div class="box-actions">
                    <div>
						<?php
                            $dd = sprintf("Total Logged Time <span class='big-font'><strong>%1s</strong></span>", $result["total_logged_time"]);
                            echo $dd;
                        ?>
					</div>
                    <div><?php
                                $dd = sprintf("Working Days Time <strong>%1s</strong>, Avg. (%2s)", $result["logged_time"], 
                                $result["average_hours_per_day"]);
                                echo $dd;
                            ?>
                     </div>
                    <div></div>
            </div>
        </div>
        <div class="box">
                    <div class="box-content">
    
                    </div>
            <div class="box-actions">
                    <div><?php
                                            $dd = sprintf("Required Time <strong>%1s d</strong> (<strong>%2s</strong>)", $result["working_days"], 
                                                $result["required_time"]);
                                            echo $dd;
                                            ?>
					</div>
                    <div><?php
                                        $dd = sprintf("Completed Time <strong>%1s</strong>, Avg. (%2s)", $result["complete_time"], 
                                            $result["average_hours_work_per_day"]);
                                        echo $dd;
                                        ?>
					</div>
                    <div><?php
                                            $dd = sprintf("Allowed Breaks <strong>%1s</strong>", $result["allowed_break"]);
                                            echo $dd;
                                        ?>
					</div>
            </div>
        </div>
        <div class="box">
                    <div class="box-content">
    
                    </div>
            <div class="box-actions">
                    <div><?php
                                            $dd = sprintf("Completed Breaks <strong>%1s</strong>", $result["breaks"]);
                                            echo $dd;
                                        ?>
					</div>
                    <div>
						<?php
        					$dd = sprintf("Extra Hours <strong>%1s</strong> + <strong>%2s (breaks)</strong>", $result["extra_work"], $result["extra_break_hour"]);
                                echo $dd;
                            ?>
                                        </div>
                    <div>
                    <?php
                    					$dd = sprintf("Weekend Hours <strong>%1s</strong>", $result["weekend_hours"]);
                                            echo $dd;
                                        ?>
					</div>
            </div>
        </div>
</fieldset>

<div class="block block-dashboard-info">
	<div class="report-header">
             <span>
                <table>
                				<tr>
                					<td><a style="float: right" class="media-print" href="#"
                						onclick="PrintDiv('report_print');"><?php echo __("Print Report")?> </a>
					</td>
				</tr>
			</table>
</span>
                	</div>
	

	
                          <?php $i=0; foreach ($result["days"] as $day) :?>
                          <?php $hours = $day["hours"];?>
                          <?php $i++;?>
                          <div
		class="<?php echo ($i%2==1?"odd":"even")?>"
		style="margin-bottom: 20px;">
		<div class="total_line">
			<span>
                            			<?php //echo __("Day");?>
                            			
                            			
                            			<strong>
                            			<?php
                            			$date=date_create($day["day"]);
                                        echo date_format($date,"Y-m-d (D)");
                                        ?>
                            			<?php //echo $day["day"];?>
                            			</strong>
			</span>
			|
			<span>
			<?php echo __("Total Hours")?>:<strong><?php echo $day["line_total_hours_format"];?></strong></span>
			</span>
			|
			<span><?php echo __("Total Hours (Work)")?>:<strong><?php echo $day["line_total_hours_work_format"];?></strong>
			</span>
				
		</div>
		<div class="block-content">
			<div class="">
				<table style="width: 100%;    line-height: 1px;    font-size: 0.9em;">
					<tr>
						<th><?php echo __("In") ?></th>
						<th><?php echo __("Out") ?></th>
						<th><?php echo __("Total") ?></th>
						<!-- <th><?php echo __("Total") ?></th>  -->
						<th><?php echo __("Type") ?></th>
					</tr>
                                         <?php foreach ($hours as $hour) :?>
                                         <?php //$totals += $hour["total"]?>
                                        	<tr>
						<td><?php echo  date_format(date_create($hour["start_time"]),"H:i:s"); ?></td>
						<td><?php echo  date_format(date_create($hour["end_time"]),"H:i:s"); ?></td>
						<td><?php echo $hour["total_time"]?></td>
						<!-- <td><?php echo $hour["total"]?></td> -->
						<td><?php echo $type[$hour["type"]]?></td>
					</tr>
                                        	 <?php endforeach;?>
                                        </table>

			</div>
		</div>
	</div>
            			<?php endforeach;?>
            </div>

